"""Compact repeated context labels without truncating provision or table text."""


def provision_text(chunk: dict) -> str:
    """Strip only the exact search labels generated by our chunker."""
    text = chunk["text"]
    title = chunk.get("document_title") or chunk.get("document_name")
    path = (chunk.get("metadata") or {}).get("hierarchy_path") or []
    # Validate the complete prefix against metadata; a document's own lines
    # starting with 'Document:' or 'Hierarchy:' must not be stripped by regex.
    prefix = f"Document: {title}\n"
    if title and text.startswith(prefix):
        text = text[len(prefix):]
        hierarchy = "Hierarchy: " + " > ".join(path) + "\n"
        if path and text.startswith(hierarchy):
            text = text[len(hierarchy):]
    elif title and chunk.get("content_type") == "table":
        # Keep table number, pages, row/column geometry and every cell value.
        prefix = f"Document: {title}. "
        if text.startswith(prefix):
            text = text[len(prefix):]
    return text


def pack_context(chunks: list[dict]) -> tuple[str, dict]:
    """Keep evidence order and citations; share labels and proven text overlaps."""
    documents, hierarchies, references = {}, {}, {}
    records = []
    for index, chunk in enumerate(chunks, 1):
        title = chunk.get("document_title") or chunk.get("document_name") or "Unknown"
        # Use IDs, not titles, to prevent equal filenames crossing documents.
        # Missing IDs get separate scopes: uncertain identity never permits reuse.
        document_key = chunk.get("document_id") or ("unknown", index)
        documents.setdefault(document_key, (f"D{len(documents) + 1}", title))
        document_label = documents[document_key][0]
        path = tuple((chunk.get("metadata") or {}).get("hierarchy_path") or [])
        parent = None
        for depth, label in enumerate(path, 1):
            # Share hierarchy prefixes, including full identifier paths. Each
            # label inherits its parent's path, so repeated '(a)' stays distinct.
            key = (document_key, path[:depth])
            hierarchies.setdefault(key, (f"H{len(hierarchies) + 1}", parent, label, document_label))
            parent = hierarchies[key][0]
        links = []
        for link in chunk.get("reference_links", []):
            ref = link["reference"]
            # The same printed reference can attach to many descendants. Define
            # it once, retaining direction and both actual endpoint identities.
            key = (document_key, link["direction"], link.get("source_node_id"),
                   link.get("target_node_id"), ref["node_type"], ref["identifier"], ref.get("sub_identifier"))
            target = ref["identifier"] + (ref.get("sub_identifier") or "")
            description = f"{document_label}: Printed reference connection ({link['direction']}): {ref['node_type']} {target} within this document."
            references.setdefault(key, (f"R{len(references) + 1}", description))
            reference_label = references[key][0]
            if reference_label not in links:
                links.append(reference_label)
        records.append({"id": f"E{index}", "chunk": chunk, "document_key": document_key,
                        "document": document_label, "hierarchy": parent,
                        "links": links, "body": provision_text(chunk)})

    # Reuse a body only within the SAME actual node, type and hierarchy. Being
    # an ancestor alone is not proof that a parent contains a child's own text.
    body_owners = {}
    for record in sorted(records, key=lambda item: -len(item["body"])):
        chunk = record["chunk"]
        node = chunk.get("node_id")
        key = (record["document_key"], node, chunk.get("content_type"),
               chunk.get("node_type"), chunk.get("identifier"), chunk.get("node_title"), record["hierarchy"])
        # With no actual node identity, retain all text rather than infer overlap.
        candidates = body_owners.setdefault(key, []) if node else []
        owner = next((item for item in candidates
                      if record["body"] and record["body"] in item["body"]), None)
        record["body_owner"] = owner["id"] if owner else record["id"]
        if owner is None:
            candidates.append(record)

    lines = ["Document labels:"]
    lines.extend(f"{label}: Source: {title}" for label, title in documents.values())
    if hierarchies:
        lines.append("Hierarchy labels (each inherits its parent's complete path):")
        lines.extend(f"{label}: {parent + ' > ' if parent else document + ' > '}{value}"
                     for label, parent, value, document in hierarchies.values())
    if references:
        lines.append("Printed reference labels:")
        lines.extend(f"{label}: {description}" for label, description in references.values())
    lines.append("Evidence (labels are pointers, not legal citation identifiers):")
    for record in records:
        chunk = record["chunk"]
        metadata = chunk.get("metadata") or {}
        block = [f"{record['id']} | Source: {record['document']}",
                 f"Node type: {chunk.get('node_type') or 'Unknown'}"]
        if chunk.get("identifier"):
            block.append(f"Identifier: {chunk['identifier']}")
        if chunk.get("node_title"):
            block.append(f"Node title: {chunk['node_title']}")
        if record["hierarchy"]:
            block.append(f"Hierarchy: {record['hierarchy']}")
        pages = metadata.get("page_numbers") or []
        if pages:
            block.append("Pages: " + ", ".join(map(str, pages)))
        if record["links"]:
            block.append("Printed references: " + ", ".join(record["links"]))
        if record["body_owner"] != record["id"]:
            block.append(f"Text: Included verbatim in {record['body_owner']} (same provision).")
        else:
            block.append(f"Text: {record['body']}")
        lines.append("\n".join(block))
    # Keep a compact, auditable mapping in the debug capture. Raw chunks remain
    # unchanged there and in source display; only the API prompt is compacted.
    mapping = [{"evidence": item["id"], "chunk_id": item["chunk"].get("chunk_id"),
                "text_evidence": item["body_owner"]} for item in records]
    return "\n\n".join(lines), {"evidence_count": len(records),
                                   "reused_bodies": sum(item["id"] != item["body_owner"] for item in records),
                                   "evidence_mapping": mapping}
